Devise branch
Josphat205/R-Blog pull request #10
Opened 2023-03-09 13:39 UTC by Josphat205

### **In This Branch**
Removed current_user method in ApplicationController, devise will provide us with one.
Installed and setup devise
- Can register a new user.
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation of email.
- Can reset passworpasswordsd.
Add styling to match wireframe

2023-03-09 16:21 UTC, CollinsTatang requested changes
Hi @Josphat205, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.
_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 16:21 UTC, CollinsTatang commented on app/views/devise/sessions/new.html.erb
> +
Hi @Josphat205 
Nice job so far implementing the different project requirements but just some little adjustments to completely meet up the project requirements.

- [ ] Please modified your devise `login` and `registration` view file to match the wireframes and their styling.
![image](https://user-images.githubusercontent.com/55596970/224085289-bf5216cb-de8f-407f-8ed0-f080380934fc.png)

2023-03-09 16:21 UTC, CollinsTatang commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] Please fix the link to your `MIT License` file the current link is broken.

2023-03-10 09:08 UTC, prolajumokeoni approved these changes
Hi @Josphat205 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - All changes requested have been implemented 🥇  
 - Design matches wireframe design ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 09:31 UTC, merged